# Generated by Django 4.0.5 on 2022-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nuevo',
            new_name='oferta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='comuna',
            field=models.CharField(default='Santiago', max_length=50),
        ),
        migrations.AddField(
            model_name='contacto',
            name='region',
            field=models.CharField(default='Region Metropolitana', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default=0, upload_to='media/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
