# Generated by Django 4.0.5 on 2022-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_nuevo_producto_oferta_contacto_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comuna',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='region',
            field=models.CharField(max_length=50),
        ),
    ]
