# Generated by Django 4.0.5 on 2022-07-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_contacto_comuna_alter_contacto_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='val',
        ),
    ]
